trigger:
- master   # Run pipeline when changes are pushed to master branch

pool:
  vmImage: 'ubuntu-latest'   # Use Ubuntu-hosted agent

steps:
# 1. Install Node.js
- task: NodeTool@0
  displayName: 'Use Node.js 20.x'
  inputs:
    versionSpec: '20.x'

# 2. Install dependencies using npm
- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    workingDir: '$(Build.SourcesDirectory)'
    command: 'install'

# 3. Copy required files (source + node_modules + views + public)
- task: CopyFiles@2
  displayName: 'Copy files to staging directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      app.js
      package.json
      package-lock.json
      node_modules/**
      views/**
      public/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'

# 4. Archive files into a ZIP
- task: ArchiveFiles@2
  displayName: 'Create ZIP archive'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/drop'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/drop/drop.zip'
    replaceExistingArchive: true

# 5. Publish artifact so it can be used in release pipeline
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
    ArtifactName: 'drop'
    publishLocation: 'Container'
